# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
    ]
