# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
    ]
