# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('posts', '0002_remove_post_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products_purchased',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
