# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_products_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products_purchased',
        ),
    ]
