# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/profile.jpg', upload_to='media'),
        ),
    ]
