# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191012_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='yet another craic addict', max_length=280),
        ),
    ]
