# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190928_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile.jpg', upload_to='profile_pics'),
        ),
    ]
