# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190930_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/media/post_images/profile.jpeg', upload_to='profile_pics'),
        ),
    ]
