# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='{{MEDIA_URL}}{{profile_pics/denzel.jpg}}', upload_to='profile_pics'),
        ),
    ]
