# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190930_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/media/post_images/denzel.jpeg', upload_to='profile_pics'),
        ),
    ]
