# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='post',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(default='cold turkey', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
